// <auto-generated />
using System;
using BusNavigate.Domain.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BusNavigate.Domain.Database.Migrations
{
    [DbContext(typeof(BusNavigateDbContext))]
    [Migration("20260923081420_AddTransitAlert")]
    partial class AddTransitAlert
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BusNavigate.Domain.Entities.BusRoute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AgencyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DataSource")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExternalRouteId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LongName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ExternalRouteId")
                        .IsUnique();

                    b.ToTable("BusRoutes");
                });

            modelBuilder.Entity("BusNavigate.Domain.Entities.BusStop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ExternalStopId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameTh")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RoadSide")
                        .HasColumnType("integer");

                    b.Property<string>("StopCode")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ExternalStopId")
                        .IsUnique();

                    b.ToTable("BusStops");
                });

            modelBuilder.Entity("BusNavigate.Domain.Entities.Direction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BusRouteId")
                        .HasColumnType("integer");

                    b.Property<int>("DirectionIndex")
                        .HasColumnType("integer");

                    b.Property<string>("ExternalDirectionKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Headsign")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BusRouteId");

                    b.HasIndex("ExternalDirectionKey")
                        .IsUnique();

                    b.ToTable("Directions");
                });

            modelBuilder.Entity("BusNavigate.Domain.Entities.Place", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DataSource")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PlaceType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.ToTable("Places");
                });

            modelBuilder.Entity("BusNavigate.Domain.Entities.RouteStop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BusStopId")
                        .HasColumnType("integer");

                    b.Property<int>("DirectionId")
                        .HasColumnType("integer");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BusStopId");

                    b.HasIndex("DirectionId", "BusStopId")
                        .IsUnique();

                    b.ToTable("RouteStops");
                });

            modelBuilder.Entity("BusNavigate.Domain.Entities.ServiceCalendar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("ExternalServiceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Friday")
                        .HasColumnType("boolean");

                    b.Property<bool>("Monday")
                        .HasColumnType("boolean");

                    b.Property<bool>("Saturday")
                        .HasColumnType("boolean");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<bool>("Sunday")
                        .HasColumnType("boolean");

                    b.Property<bool>("Thursday")
                        .HasColumnType("boolean");

                    b.Property<bool>("Tuesday")
                        .HasColumnType("boolean");

                    b.Property<bool>("Wednesday")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ExternalServiceId")
                        .IsUnique();

                    b.ToTable("ServiceCalendars");
                });

            modelBuilder.Entity("BusNavigate.Domain.Entities.ServiceException", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("ExceptionDate")
                        .HasColumnType("date");

                    b.Property<int>("ExceptionType")
                        .HasColumnType("integer");

                    b.Property<int>("ServiceCalendarId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ServiceCalendarId", "ExceptionDate")
                        .IsUnique();

                    b.ToTable("ServiceExceptions");
                });

            modelBuilder.Entity("BusNavigate.Domain.Entities.TransitAlert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BusRouteId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int?>("DirectionId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DirectionId");

                    b.HasIndex("BusRouteId", "DirectionId");

                    b.ToTable("TransitAlerts");
                });

            modelBuilder.Entity("BusNavigate.Domain.Entities.TravelSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AlightingStopId")
                        .HasColumnType("integer");

                    b.Property<int>("BoardingStopId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DirectionId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastActivityAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AlightingStopId");

                    b.HasIndex("BoardingStopId");

                    b.HasIndex("DirectionId");

                    b.HasIndex("UserId");

                    b.ToTable("TravelSessions");
                });

            modelBuilder.Entity("BusNavigate.Domain.Entities.Trip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DirectionId")
                        .HasColumnType("integer");

                    b.Property<string>("ExternalTripId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ServiceCalendarId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DirectionId");

                    b.HasIndex("ExternalTripId")
                        .IsUnique();

                    b.HasIndex("ServiceCalendarId");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("BusNavigate.Domain.Entities.TripStopTime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<TimeSpan>("ArrivalTime")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("DepartureTime")
                        .HasColumnType("interval");

                    b.Property<int>("RouteStopId")
                        .HasColumnType("integer");

                    b.Property<int>("TripId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RouteStopId");

                    b.HasIndex("TripId", "RouteStopId")
                        .IsUnique();

                    b.ToTable("TripStopTimes");
                });

            modelBuilder.Entity("BusNavigate.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalDeviceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ExternalDeviceId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BusNavigate.Domain.Entities.Direction", b =>
                {
                    b.HasOne("BusNavigate.Domain.Entities.BusRoute", "BusRoute")
                        .WithMany("Directions")
                        .HasForeignKey("BusRouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusRoute");
                });

            modelBuilder.Entity("BusNavigate.Domain.Entities.RouteStop", b =>
                {
                    b.HasOne("BusNavigate.Domain.Entities.BusStop", "BusStop")
                        .WithMany("RouteStops")
                        .HasForeignKey("BusStopId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BusNavigate.Domain.Entities.Direction", "Direction")
                        .WithMany("RouteStops")
                        .HasForeignKey("DirectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusStop");

                    b.Navigation("Direction");
                });

            modelBuilder.Entity("BusNavigate.Domain.Entities.ServiceException", b =>
                {
                    b.HasOne("BusNavigate.Domain.Entities.ServiceCalendar", "ServiceCalendar")
                        .WithMany("ServiceExceptions")
                        .HasForeignKey("ServiceCalendarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceCalendar");
                });

            modelBuilder.Entity("BusNavigate.Domain.Entities.TransitAlert", b =>
                {
                    b.HasOne("BusNavigate.Domain.Entities.BusRoute", "BusRoute")
                        .WithMany()
                        .HasForeignKey("BusRouteId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BusNavigate.Domain.Entities.Direction", "Direction")
                        .WithMany()
                        .HasForeignKey("DirectionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("BusRoute");

                    b.Navigation("Direction");
                });

            modelBuilder.Entity("BusNavigate.Domain.Entities.TravelSession", b =>
                {
                    b.HasOne("BusNavigate.Domain.Entities.BusStop", "AlightingStop")
                        .WithMany()
                        .HasForeignKey("AlightingStopId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BusNavigate.Domain.Entities.BusStop", "BoardingStop")
                        .WithMany()
                        .HasForeignKey("BoardingStopId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BusNavigate.Domain.Entities.Direction", "Direction")
                        .WithMany()
                        .HasForeignKey("DirectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BusNavigate.Domain.Entities.User", "User")
                        .WithMany("TravelSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlightingStop");

                    b.Navigation("BoardingStop");

                    b.Navigation("Direction");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BusNavigate.Domain.Entities.Trip", b =>
                {
                    b.HasOne("BusNavigate.Domain.Entities.Direction", "Direction")
                        .WithMany("Trips")
                        .HasForeignKey("DirectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusNavigate.Domain.Entities.ServiceCalendar", "ServiceCalendar")
                        .WithMany("Trips")
                        .HasForeignKey("ServiceCalendarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Direction");

                    b.Navigation("ServiceCalendar");
                });

            modelBuilder.Entity("BusNavigate.Domain.Entities.TripStopTime", b =>
                {
                    b.HasOne("BusNavigate.Domain.Entities.RouteStop", "RouteStop")
                        .WithMany("TripStopTimes")
                        .HasForeignKey("RouteStopId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BusNavigate.Domain.Entities.Trip", "Trip")
                        .WithMany("TripStopTimes")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RouteStop");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("BusNavigate.Domain.Entities.BusRoute", b =>
                {
                    b.Navigation("Directions");
                });

            modelBuilder.Entity("BusNavigate.Domain.Entities.BusStop", b =>
                {
                    b.Navigation("RouteStops");
                });

            modelBuilder.Entity("BusNavigate.Domain.Entities.Direction", b =>
                {
                    b.Navigation("RouteStops");

                    b.Navigation("Trips");
                });

            modelBuilder.Entity("BusNavigate.Domain.Entities.RouteStop", b =>
                {
                    b.Navigation("TripStopTimes");
                });

            modelBuilder.Entity("BusNavigate.Domain.Entities.ServiceCalendar", b =>
                {
                    b.Navigation("ServiceExceptions");

                    b.Navigation("Trips");
                });

            modelBuilder.Entity("BusNavigate.Domain.Entities.Trip", b =>
                {
                    b.Navigation("TripStopTimes");
                });

            modelBuilder.Entity("BusNavigate.Domain.Entities.User", b =>
                {
                    b.Navigation("TravelSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
